spring:
  kafka:
    producer:
      bootstrap-servers:
        - localhost:9092
      key-serializer:
        ['org.apache.kafka.common.serialization.StringDeserializer']
      value-serializer:
        ['org.apache.kafka.common.serialization.StringDeserializer']

server:
  port: 8045